
sudo: required

language: julia

services:
  - docker

os:
  - osx
  - linux

julia:
  - 1.0
  - 1.3
  - nightly

matrix:
  allow_failures:
  - julia: nightly

notifications:
  email: false

after_success:
  - julia -e 'import Pkg, JDBC; cd(joinpath(dirname(pathof(JDBC)),"..")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  - julia -e 'import Pkg; Pkg.add("Documenter")'
  - julia -e 'import JDBC; cd(joinpath(dirname(pathof(JDBC)),"..")); include(joinpath("docs", "make.jl"))'
